### ISSUE TITLE
wrong default value for router option

### ISSUE THREAD

**Issue by cybernetlab** [InDIOS/vue-ts-decorate#2]
You have wrong default value for `router` option [here](https://github.com/InDIOS/vue-ts-decorate/blob/master/utils/utilities.ts#L57).

If I have `<router-view>` components in my template it makes me following error:

```
Uncaught TypeError: this._router.init is not a function
beforeCreate @ vue-router.common.js:421
callHook @ vue.common.js:2754
Vue._init @ vue.common.js:3377
VueComponent @ vue.common.js:3500
createComponentInstanceForVnode @ vue.common.js:1724
init @ vue.common.js:1734
(anonymous function) @ vue.common.js:1894
createComponent @ vue.common.js:4174
createElm @ vue.common.js:4117
createChildren @ vue.common.js:4242
createElm @ vue.common.js:4150
patch @ vue.common.js:4569
Vue._update @ vue.common.js:2635
updateComponent @ vue.common.js:2609
get @ vue.common.js:2934
Watcher @ vue.common.js:2926
Vue._mount @ vue.common.js:2608
Vue$3.$mount @ vue.common.js:6178
Vue$3.$mount @ vue.common.js:8549
init @ vue.common.js:1740
createComponent @ vue.common.js:4174
createElm @ vue.common.js:4117
patch @ vue.common.js:4605
Vue._update @ vue.common.js:2635
updateComponent @ vue.common.js:2609
get @ vue.common.js:2934
Watcher @ vue.common.js:2926
Vue._mount @ vue.common.js:2608
Vue$3.$mount @ vue.common.js:6178
Vue$3.$mount @ vue.common.js:8549
(anonymous function) @ main.ts:46
__webpack_require__ @ bootstrap a311129…:19
(anonymous function) @ bootstrap a311129…:65
(anonymous function) @ bootstrap a311129…:65
```

After some digging I found that VueRouter init() function expects that if `router` in options that it should be a VueRouter instance that have `init` method. See [here](https://github.com/vuejs/vue-router/blob/dev/src/install.js#L22). But you set this option to empty object if `router` is not setted in options that cause above error. After deleting [line #57 in your utilities.ts](https://github.com/InDIOS/vue-ts-decorate/blob/master/utils/utilities.ts#L57) all works fine.

**Comment by InDIOS** [comment]
Apparently that is an error in the cleanOptions function. I fixed that error. Try again with this update and tell me how did it go.
