### ISSUE TITLE
Cannot find namespace 'himalayajs'.

### ISSUE THREAD

**Issue by maelgrove** [InDIOS/vue-ts-decorate#3]
I know this is an exact duplicate of #1, but this still doesn't seem to be fixed even though the issue has been closed.

For me, it's the _at-loader_ (`awesome-typescript-loader` package) which complains during webpack build. The typings itself are not included within the current version of the npm package (_1.0.0_), but even after I downloaded them myself from the repo and included the file in `tsconfig.json`, the error still persists.

**error message**

    ERROR in [at-loader] ./node_modules/vue-ts-decorate/utils/tools.ts:149:20
        TS2503: Cannot find namespace 'himalayajs'.

    ERROR in [at-loader] ./node_modules/vue-ts-decorate/utils/tools.ts:167:23
        TS2503: Cannot find namespace 'absurdCss'.

**env**

    Node: 6.10.3
    Vue: 2.3.3
    ts: 2.3.2

**Comment by InDIOS** [comment]
Sorry for the delay in replying. I have to update the npm package as soon as possible. There is some changes that are crucial but my time is limited. In the next days i fixed that error and others that i found it. Don't worry about the changes, all are internal.

**Comment by maelgrove** [comment]
Hey there. Fiddled around with the latest release you published to the NPM repo and things seem to work now. Thank you very much and keep up the good work. This is by far the most complete vue/typescript decoration lib. :)
